"""Synthetic sample data generator (Bloomberg-export style).

Produces CSV files the BloombergExportAdapter can ingest end-to-end, so the
platform can be developed and demoed off-terminal. EVERYTHING generated here
is synthetic: headlines are prefixed with "[SYNTHETIC]", a README.txt marker
is written next to the files, and SAMPLE_SOURCE_NOTE states it plainly.

Prices follow a seeded geometric Brownian motion with per-ticker drift and
volatility; outputs are fully reproducible for a given seed.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

from quant_platform.core.config import load_yaml_config

SAMPLE_SOURCE_NOTE = "SYNTHETIC / SAMPLE DATA — not real Bloomberg data"

_PRICES_FILE = "synthetic_prices.csv"
_NEWS_FILE = "news.csv"

_HEADLINE_TEMPLATES = [
    "{t} reports record quarterly revenue in fabricated earnings release",
    "{t} announces imaginary next-generation product lineup",
    "{t} shares move on invented analyst upgrade",
    "{t} signs fictional multi-year supply agreement",
    "{t} faces made-up regulatory inquiry, sources say",
    "{t} unveils synthetic capacity expansion plan",
]

_BODY_TEMPLATE = (
    "This is an automatically generated SAMPLE news item about {t}. "
    "It exists only to exercise the platform's data pipeline. "
    "No statement in this item is real."
)


def _default_tickers() -> list[str]:
    return list(load_yaml_config("universe")["college_test_universe"])


def _write_readme(out_dir: Path) -> Path:
    readme = out_dir / "README.txt"
    readme.write_text(
        f"{SAMPLE_SOURCE_NOTE}\n\n"
        "Generated by quant_platform.data.sample_data for development/demo use.\n"
        "Prices are a seeded geometric Brownian motion; news headlines are\n"
        'prefixed with "[SYNTHETIC]". Do not treat any value here as real.\n',
        encoding="utf-8",
    )
    return readme


def generate_sample_export(
    out_dir: Path | str,
    tickers: list[str] | None = None,
    start: str = "2023-01-01",
    end: str = "2025-06-30",
    seed: int = 42,
) -> Path:
    """Write a Bloomberg-export-style wide CSV of synthetic daily OHLCV bars.

    Columns: security,date,PX_OPEN,PX_HIGH,PX_LOW,PX_LAST,PX_VOLUME,CUR_MKT_CAP.
    Securities are written in ``NVDA US Equity`` style. Returns the CSV path.
    """
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    tickers = list(tickers) if tickers else _default_tickers()
    dates = pd.bdate_range(start, end)
    n = len(dates)
    rng = np.random.default_rng(seed)

    frames = []
    for i, ticker in enumerate(tickers):
        drift = 0.0001 + 0.0004 * rng.random()  # per-ticker daily drift
        vol = 0.010 + 0.018 * rng.random()  # per-ticker daily volatility
        shocks = rng.normal(drift, vol, n)
        close = 40.0 * (1.0 + 1.7 * i) * np.exp(np.cumsum(shocks))
        prev_close = np.concatenate([[close[0] * np.exp(-shocks[0])], close[:-1]])
        open_ = prev_close * np.exp(rng.normal(0.0, vol / 4, n))
        high = np.maximum(open_, close) * np.exp(np.abs(rng.normal(0.0, vol / 6, n)))
        low = np.minimum(open_, close) * np.exp(-np.abs(rng.normal(0.0, vol / 6, n)))
        volume = rng.integers(1_000_000, 60_000_000, n).astype(float)
        shares_out = 1e8 * (1 + i)
        frames.append(
            pd.DataFrame(
                {
                    "security": f"{ticker} US Equity",
                    "date": dates.strftime("%Y-%m-%d"),
                    "PX_OPEN": np.round(open_, 2),
                    "PX_HIGH": np.round(high, 2),
                    "PX_LOW": np.round(low, 2),
                    "PX_LAST": np.round(close, 2),
                    "PX_VOLUME": volume,
                    "CUR_MKT_CAP": np.round(close * shares_out, 0),
                }
            )
        )

    df = pd.concat(frames, ignore_index=True)
    path = out / _PRICES_FILE
    df.to_csv(path, index=False)
    _write_readme(out)
    return path


def generate_sample_news(
    out_dir: Path | str,
    tickers: list[str] | None = None,
    start: str = "2023-01-01",
    end: str = "2025-06-30",
    seed: int = 42,
    per_ticker: int = 12,
) -> Path:
    """Write obviously-synthetic sample news to ``<out_dir>/news/news.csv``.

    Columns: security,date,headline,body. Every headline is prefixed with
    "[SYNTHETIC]". Kept in a ``news/`` subdirectory so the BloombergExportAdapter
    (which ingests every CSV directly under its inbox) never trips over it.
    """
    out = Path(out_dir) / "news"
    out.mkdir(parents=True, exist_ok=True)
    tickers = list(tickers) if tickers else _default_tickers()
    dates = pd.bdate_range(start, end)
    rng = np.random.default_rng(seed + 1)

    records = []
    for ticker in tickers:
        chosen = rng.choice(len(dates), size=min(per_ticker, len(dates)), replace=False)
        for idx in sorted(chosen):
            template = _HEADLINE_TEMPLATES[rng.integers(0, len(_HEADLINE_TEMPLATES))]
            records.append(
                {
                    "security": f"{ticker} US Equity",
                    "date": dates[idx].strftime("%Y-%m-%d"),
                    "headline": f"[SYNTHETIC] {template.format(t=ticker)}",
                    "body": _BODY_TEMPLATE.format(t=ticker),
                }
            )

    path = out / _NEWS_FILE
    pd.DataFrame(records).to_csv(path, index=False)
    _write_readme(Path(out_dir))
    return path
